filebeat.inputs:
- type: container
  paths:
    - /var/lib/docker/containers/*/*.log

processors:
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: ["http://10.10.93.47:9200"]

setup.kibana:
  host: "http://10.10.93.47:5601"

